# -*- coding: utf-8 -*-
"""FAQ Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZirMjYIcRmcXJkG33U2A6O-eF_sG5xS

# Install Required Libraries
"""

# =========================================================
# INSTALL REQUIRED LIBRARIES
# =========================================================

!pip -q install gradio sentence-transformers faiss-cpu pandas numpy tqdm

# =========================================================
# IMPORTS
# =========================================================

import os
import faiss
import random
import pandas as pd
import numpy as np
import gradio as gr

from tqdm.auto import tqdm
from sentence_transformers import SentenceTransformer
from datetime import datetime

# Silence warnings
import warnings
warnings.filterwarnings("ignore")

# =========================================================
# GENERATE SYNTHETIC FAQ DATASET
# =========================================================

categories = {
    "General AI": [
        "What is artificial intelligence?",
        "How does AI work?",
        "What is machine learning?",
        "What is deep learning?",
        "What are neural networks?",
        "What is generative AI?",
        "What is computer vision?",
        "What is NLP?",
        "What are AI agents?",
        "What is reinforcement learning?"
    ],

    "AI Libraries": [
        "What is TensorFlow?",
        "What is PyTorch?",
        "What is Scikit-learn?",
        "What is OpenCV?",
        "What is Hugging Face?",
        "What is LangChain?",
        "What is Pandas?",
        "What is NumPy?",
        "What is Matplotlib?",
        "What is Keras?"
    ],

    "AI Frameworks": [
        "What is LangGraph?",
        "What is Haystack?",
        "What is Rasa?",
        "What is MLflow?",
        "What is FastAPI?",
        "What is Streamlit?",
        "What is Gradio?",
        "What is Ray?",
        "What is ONNX?",
        "What is OpenMMLab?"
    ],

    "AI Platforms": [
        "What is Google Colab?",
        "What is Kaggle?",
        "What is Hugging Face?",
        "What is Azure AI?",
        "What is AWS SageMaker?",
        "What is Vertex AI?",
        "What is Databricks?",
        "What is IBM Watson?",
        "What is OpenAI API?",
        "What is Replicate?"
    ]
}

templates = [
    "Explain {} in simple terms.",
    "Can you describe {}?",
    "How is {} used in AI?",
    "What are the benefits of {}?",
    "Why is {} important?",
    "How do beginners learn {}?",
    "What problems does {} solve?",
    "Give an overview of {}.",
    "What are applications of {}?",
    "How does {} compare to alternatives?"
]

answers_template = """
{topic} is an important concept in the field of Artificial Intelligence and modern software systems.
It is commonly used for building scalable, intelligent, and data-driven applications.
Developers and researchers use {topic} for automation, machine learning, NLP, computer vision,
data analysis, and AI-powered systems.
"""

faq_rows = []

# Create 1000+ rows
for category, topics in categories.items():
    for topic in topics:
        for template in templates:
            for i in range(3):

                question = template.format(topic)

                answer = answers_template.format(topic=topic)

                faq_rows.append({
                    "question": question,
                    "answer": answer,
                    "category": category
                })

faq_df = pd.DataFrame(faq_rows)

# Shuffle dataset
faq_df = faq_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("✅ FAQ Dataset Created")
print("📊 Total Rows:", len(faq_df))

faq_df.head()

# =========================================================
# OPTIONAL: LOAD YOUR OWN CSV FILE
# =========================================================

# Replace with your own CSV path if needed
# CSV must contain:
# question | answer | category

"""
Example:

faq_df = pd.read_csv("/content/your_faq_dataset.csv")
"""

# Ensure required columns exist
required_columns = {"question", "answer", "category"}

if not required_columns.issubset(set(faq_df.columns)):
    raise ValueError("Dataset must contain question, answer, and category columns.")

print("✅ Dataset Ready")

# =========================================================
# LOAD EMBEDDING MODEL
# =========================================================

MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

print("🔄 Loading embedding model...")

model = SentenceTransformer(MODEL_NAME)

print("✅ Model loaded successfully")

# =========================================================
# GENERATE EMBEDDINGS
# =========================================================

questions = faq_df["question"].fillna("").tolist()

print("🔄 Generating embeddings...")

embeddings = model.encode(
    questions,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("✅ Embeddings Generated")
print("Embedding Shape:", embeddings.shape)

# =========================================================
# BUILD FAISS INDEX
# =========================================================

dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

# Normalize vectors for cosine similarity
faiss.normalize_L2(embeddings)

index.add(embeddings)

print("✅ FAISS Index Created")
print("📦 Total Indexed Questions:", index.ntotal)

# =========================================================
# SEMANTIC SEARCH FUNCTION
# =========================================================

def semantic_search(
    query,
    category_filter="All",
    top_k=5
):
    """
    Semantic FAQ Retrieval using Sentence Transformers + FAISS
    """

    try:

        # -----------------------------
        # Validate Query
        # -----------------------------
        if query is None or not str(query).strip():
            return {
                "answer": "⚠️ Please enter a valid question.",
                "confidence": 0,
                "related": []
            }

        query = str(query).strip()

        # -----------------------------
        # Encode Query
        # -----------------------------
        query_embedding = model.encode(
            [query],
            convert_to_numpy=True
        )

        faiss.normalize_L2(query_embedding)

        # -----------------------------
        # Search FAISS
        # -----------------------------
        scores, indices = index.search(
            query_embedding,
            min(top_k * 3, len(faq_df))
        )

        indices = indices[0]
        scores = scores[0]

        # -----------------------------
        # Build Results
        # -----------------------------
        results = []

        for idx, score in zip(indices, scores):

            # Prevent index errors
            if idx < 0 or idx >= len(faq_df):
                continue

            row = faq_df.iloc[idx]

            category = row["category"]

            # Apply category filter
            if category_filter != "All":
                if category != category_filter:
                    continue

            results.append({
                "question": row["question"],
                "answer": row["answer"],
                "category": category,
                "score": float(score)
            })

        # -----------------------------
        # No Results
        # -----------------------------
        if len(results) == 0:
            return {
                "answer": "❌ No matching FAQ found.",
                "confidence": 0,
                "related": []
            }

        # -----------------------------
        # Best Match
        # -----------------------------
        best = results[0]

        confidence = int(
            max(0, min(best["score"] * 100, 100))
        )

        # -----------------------------
        # Related Questions
        # -----------------------------
        related = []

        for item in results[1:4]:
            related.append(item["question"])

        return {
            "answer": best["answer"],
            "confidence": confidence,
            "related": related
        }

    except Exception as e:

        return {
            "answer": f"⚠️ Error occurred: {str(e)}",
            "confidence": 0,
            "related": []
        }

# =========================================================
# EXPORT CHAT HISTORY
# =========================================================

def export_chat(chat_history):

    try:

        if not chat_history:
            return None

        filename = f"chat_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"

        with open(filename, "w", encoding="utf-8") as f:

            for user_msg, bot_msg in chat_history:
                f.write(f"USER: {user_msg}\n")
                f.write(f"BOT : {bot_msg}\n")
                f.write("\n" + "="*60 + "\n\n")

        return filename

    except Exception as e:
        print("Export Error:", e)
        return None

# =========================================================
# CHATBOT RESPONSE FUNCTION
# =========================================================

def chatbot_response(message, history, category):

    try:

        if history is None:
            history = []

        result = semantic_search(
            query=message,
            category_filter=category,
            top_k=5
        )

        answer = result["answer"]
        confidence = result["confidence"]
        related = result["related"]

        # -----------------------------
        # Confidence Bar
        # -----------------------------
        bar_length = 20

        filled = int((confidence / 100) * bar_length)

        progress_bar = (
            "🟩" * filled +
            "⬜" * (bar_length - filled)
        )

        response = f"""
### 🤖 Answer

{answer}

---

### 📊 Confidence Score

{confidence}%
{progress_bar}

"""

        # -----------------------------
        # Related Questions
        # -----------------------------
        if related:

            response += "\n### 🔗 Related Questions\n"

            for q in related:
                response += f"- {q}\n"

        history.append((message, response))

        return history, history

    except Exception as e:

        error_response = f"⚠️ System Error: {str(e)}"

        history.append((message, error_response))

        return history, history

# =========================================================
# BROWSE FAQS
# =========================================================

def browse_faqs(category):

    try:

        data = faq_df.copy()

        if category != "All":
            data = data[data["category"] == category]

        if len(data) == 0:
            return pd.DataFrame({
                "Message": ["No FAQs found"]
            })

        return data[["question", "answer", "category"]]

    except Exception as e:

        return pd.DataFrame({
            "Error": [str(e)]
        })

# =========================================================
# BUILD PROFESSIONAL GRADIO UI
# =========================================================

custom_css = """
body {
    background-color: #0f172a;
}

.gradio-container {
    font-family: 'Inter', sans-serif;
}

footer {
    display: none !important;
}
"""

theme = gr.themes.Soft(
    primary_hue="blue",
    secondary_hue="slate",
    neutral_hue="slate"
)

def build_app():

    with gr.Blocks(
        theme=theme,
        css=custom_css,
        title="Advanced FAQ Chatbot"
    ) as demo:

        gr.Markdown("""
        # 🤖 Advanced AI FAQ Chatbot

        ### Semantic Search + FAISS + Sentence Transformers

        Ask AI-related questions and receive intelligent answers instantly.
        """)

        with gr.Tabs():

            # =================================================
            # CHAT TAB
            # =================================================
            with gr.Tab("💬 Chat Assistant"):

                category_dropdown = gr.Dropdown(
                    choices=["All"] + sorted(faq_df["category"].unique().tolist()),
                    value="All",
                    label="Filter by Category"
                )

                chatbot = gr.Chatbot(
                    height=500,
                    bubble_full_width=False
                )

                msg = gr.Textbox(
                    placeholder="Ask your AI question...",
                    label="Your Question"
                )

                state = gr.State([])

                with gr.Row():

                    send_btn = gr.Button("🚀 Send", variant="primary")

                    clear_btn = gr.Button("🧹 Clear Chat")

                    export_btn = gr.Button("📤 Export Chat")

                export_file = gr.File(label="Download Chat")

                # Events
                send_btn.click(
                    chatbot_response,
                    inputs=[msg, state, category_dropdown],
                    outputs=[chatbot, state]
                )

                msg.submit(
                    chatbot_response,
                    inputs=[msg, state, category_dropdown],
                    outputs=[chatbot, state]
                )

                clear_btn.click(
                    lambda: ([], []),
                    outputs=[chatbot, state]
                )

                export_btn.click(
                    export_chat,
                    inputs=[state],
                    outputs=[export_file]
                )

            # =================================================
            # BROWSE FAQ TAB
            # =================================================
            with gr.Tab("📚 Browse FAQs"):

                browse_dropdown = gr.Dropdown(
                    choices=["All"] + sorted(faq_df["category"].unique().tolist()),
                    value="All",
                    label="Select Category"
                )

                faq_table = gr.Dataframe(
                    interactive=False,
                    wrap=True
                )

                browse_dropdown.change(
                    browse_faqs,
                    inputs=[browse_dropdown],
                    outputs=[faq_table]
                )

                demo.load(
                    lambda: browse_faqs("All"),
                    outputs=[faq_table]
                )

            # =================================================
            # HOW IT WORKS TAB
            # =================================================
            with gr.Tab("🛠️ How It Works"):

                gr.Markdown("""
                # 🔍 Technology Stack

                ## Core Components

                | Component | Purpose |
                |---|---|
                | Sentence Transformers | Semantic embeddings |
                | all-MiniLM-L6-v2 | Lightweight embedding model |
                | FAISS | Fast vector similarity search |
                | Gradio | Web application UI |
                | Pandas | Dataset handling |
                | NumPy | Numerical processing |

                ---

                ## Workflow

                1. User submits a question
                2. Question converted into vector embedding
                3. FAISS searches most similar FAQ
                4. Best answer returned
                5. Confidence score calculated
                6. Related questions displayed

                ---

                ## Features

                ✅ Semantic Search
                ✅ FAISS Fast Retrieval
                ✅ Related Questions
                ✅ Confidence Visualization
                ✅ Category Filtering
                ✅ Chat Export
                ✅ FAQ Browser
                ✅ Error Handling
                ✅ Professional UI
                """)

    return demo

# =========================================================
# LAUNCH APPLICATION
# =========================================================

if __name__ == "__main__":

    print("=" * 60)
    print("🚀 STARTING ADVANCED FAQ CHATBOT")
    print("=" * 60)

    print("📦 Loading Application...")
    app = build_app()

    print("✅ Application Ready")
    print("🌐 Launching Gradio Interface...")
    print("📡 Share link will appear below")
    print("=" * 60)

    app.launch(
        share=True,
        debug=False
    )

